version: '{branch}-{build}'

before_build:
  - nuget restore Unity-Technologies-networking/Networking.sln

build:
  project: Unity-Technologies-networking/Networking.sln
  verbosity: minimal
  
artifacts:
  - path: Unity-Technologies-networking/Output
    name: HLAPI_CE_2018.1_fixes

image: Visual Studio 2017

deploy:
  description: 'HLAPI community edition $(APPVEYOR_REPO_BRANCH) '
  provider: GitHub
  auth_token:
    secure: MMIxeq4Jg5xypACSCTJn60ua+/Zj/bJkFUv/SHBPTVIa+jQn3iLZM20PIqD+Eeun # your encrypted token from GitHub
  artifact: Unity-Technologies-networking\HLAPI_CE_2018.1_fixes.zip            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
