version: '{branch}-{build}'

before_build:
  - nuget restore Unity-Technologies-networking/Networking.sln

build:
  project: Unity-Technologies-networking/Networking.sln
  verbosity: minimal
  
artifacts:
  - path: Unity-Technologies-networking/Output/**/*

image: Visual Studio 2017

test_script:
  - Unity-Technologies-networking\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"Unity-Technologies-networking\UnityEngine.Networking.Tests\bin\Debug\UnityEngine.Networking.Tests.dll" -output:"coverage.xml" -filter:"+[UnityEngine.Networking*]* -[UnityEngine.Networking.Tests*]* "

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" 
